name: Gradle Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish
        env:
          GITHUB_PACKAGE_USERNAME: myConsciousness
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: ./gradlew publish
